### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KGIII/pino-twitter#162]
```
System: openSUSE 11.2 x86_64

Dependencies:

vala 0.7.10-2.2
libnotify 0.4.5-7.2
libsoup 2.29.91-2.1
libwebkit 1.1.90-1.2
libgee2 0.5.0-36.1
libunique 1.1.6-3.1
gtkspell 2.0.15-5.1

Log:

dc@linux-t66v:~> pino

(pino:27172): Gtk-WARNING **: Unable to locate theme engine in module_path:
"aurora",

(pino:27172): Gtk-WARNING **: Unable to locate theme engine in module_path:
"aurora",

(pino:27172): Gtk-WARNING **: Unable to locate theme engine in module_path:
"aurora",

(pino:27172): Gtk-WARNING **: Unable to locate theme engine in module_path:
"aurora",

** (pino:27172): CRITICAL **: userpic_set_default: assertion `self != NULL'
failed

(pino:27172): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion
`GTK_IS_WIDGET (widget)' failed

(pino:27172): Gtk-CRITICAL **: gtk_label_set_markup: assertion
`GTK_IS_LABEL (label)' failed

(pino:27172): Gtk-CRITICAL **: gtk_label_set_markup: assertion
`GTK_IS_LABEL (label)' failed

(pino:27172): Gtk-CRITICAL **: gtk_label_set_markup: assertion
`GTK_IS_LABEL (label)' failed

(pino:27172): Gtk-CRITICAL **: gtk_widget_hide: assertion `GTK_IS_WIDGET
(widget)' failed

(pino:27172): Gtk-CRITICAL **: gtk_label_set_markup: assertion
`GTK_IS_LABEL (label)' failed

(pino:27172): Gtk-CRITICAL **: gtk_widget_hide: assertion `GTK_IS_WIDGET
(widget)' failed

(pino:27172): Gtk-CRITICAL **: gtk_widget_hide: assertion `GTK_IS_WIDGET
(widget)' failed

(pino:27172): Gtk-CRITICAL **: gtk_widget_hide: assertion `GTK_IS_WIDGET
(widget)' failed

(pino:27172): Gtk-CRITICAL **: gtk_widget_hide: assertion `GTK_IS_WIDGET
(widget)' failed

(pino:27172): Gtk-CRITICAL **: gtk_text_view_get_buffer: assertion
`GTK_IS_TEXT_VIEW (text_view)' failed

(pino:27172): GLib-GObject-CRITICAL **: g_object_set: assertion
`G_IS_OBJECT (object)' failed

** (pino:27172): CRITICAL **: auth_account_get_service: assertion `self !=
NULL' failed

** (pino:27172): CRITICAL **: auth_account_get_login: assertion `self !=
NULL' failed

** (pino:27172): CRITICAL **: auth_account_get_login: assertion `self !=
NULL' failed

(pino:27172): Gtk-CRITICAL **: gtk_widget_set_sensitive: assertion
`GTK_IS_WIDGET (widget)' failed

** (pino:27172): WARNING **: rest_api_timeline.vala:74:
https://twapi.net/statuses/home_timeline.xml

** (pino:27172): WARNING **: rest_api_abstract.vala:185: 1
Segmentation fault




```

Original issue reported on code.google.com by `doublec...@gmail.com` on 30 Mar 2010 at 3:48

**Comment by GoogleCodeExporter** [comment]
```
Just install aurora engine for gnome in your opensuse powered computer. Looks 
like it
is missing. Not a pino bug, or am I wrong ?
```

Original comment by `fredbez...@gmail.com` on 4 Apr 2010 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
No, this has nothing to do with Aurora engine (see how that are just GTK 
warnings?) -
the segfault happens elsewhere.

@doublechou: Can you please give a GDB backtrace of the corefile to have some 
more
details? Do: gdb /path/to/pino /path/to/pino.core and type 'bt'.

I'm asking because this looks like a similar crash as I see it on FreeBSD 
-CURRENT
and i suspect glib being the issue somehow.

Thanks,
steinex
```

Original comment by `steinex...@googlemail.com` on 4 Apr 2010 at 3:21

**Comment by GoogleCodeExporter** [comment]
```
Hi, steinex,

Here we go.

#0  0x0000000000423695 in rest_api_rest_api_timeline_parse_timeline ()
#1  0x0000000000423397 in rest_api_rest_api_timeline_real_get_timeline ()
#2  0x000000000042b88d in rest_api_rest_api_abstract_get_timeline ()
#3  0x000000000040a6d7 in timeline_list_real_update ()
#4  0x000000000041f45c in timeline_list_abstract_update ()
#5  0x00000000004324a3 in main_window_refresh_action ()
#6  0x0000000000430dae in main_window_construct ()
#7  0x0000000000430ed4 in main_window_new ()
#8  0x00000000004392b2 in main_main ()
#9  0x0000000000439347 in main ()

more detail in the attachment.

Good Luck.

Marguerite.
```

Original comment by `doublec...@gmail.com` on 5 Apr 2010 at 2:32

Attachments:
- [pino_bugtrace](https://storage.googleapis.com/google-code-attachments/pino-twitter/issue-162/comment-3/pino_bugtrace)
