### ISSUE TITLE
"Checking for gthread-2.0 : Traceback (most recent call last)"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KGIII/pino-twitter#326]
```
I'm running Arch Linux (x86-64), and I cant install Pino via Arch AUR.

==> Starting build()...
Checking for program gcc,cc              : ok /usr/bin/gcc 
Checking for program cpp                 : ok /usr/bin/cpp 
Checking for program ar                  : ok /usr/bin/ar 
Checking for program ranlib              : ok /usr/bin/ranlib 
Checking for gcc                         : ok  
Checking for program valac               : ok /usr/bin/valac 
Checking for gthread-2.0                 : Traceback (most recent call last):
  File "/home/johan/pkgbuilds/pino/src/pino-0.2.10/.waf3-1.5.9-d1e0349fc8937631a656fb8ea7e99063/wafadmin/Utils.py", line 414, in recurse
    txt=readf(base+'_'+name,m='rU')
  File "/home/johan/pkgbuilds/pino/src/pino-0.2.10/.waf3-1.5.9-d1e0349fc8937631a656fb8ea7e99063/wafadmin/Utils.py", line 379, in readf
    f=open(fname,m)
IOError: [Errno 2] No such file or directory: 
'/home/johan/pkgbuilds/pino/src/pino-0.2.10/wscript_configure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./waf", line 148, in <module>
    Aborting...

Whats up with "gthread-2.0"?
```

Original issue reported on code.google.com by `58desi...@gmail.com` on 30 Oct 2010 at 1:46

**Comment by GoogleCodeExporter** [comment]
```
Anyone?
```

Original comment by `58desi...@gmail.com` on 19 Feb 2011 at 12:43
